include:
- ./func/*
kind: ArchiveUploadSpec
name: func-635h

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-ticket-fn-1b8a9742-85df-4a4b-91cf-b2eeb4904f51
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: update-ticket-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-635h
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T14:13:26Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-ticket-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 5
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: update-ticket-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_ticket_comments
    packageref:
      name: update-ticket-fn-1b8a9742-85df-4a4b-91cf-b2eeb4904f51
      namespace: default
  requestsPerPod: 1
  resources: {}
