include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-P34h

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sup-tckt-comment-fn-48039350-e3da-4e08-80c8-343f66779ebc
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-P34h
  environment:
    name: sup-tckt-comment-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T20:15:51Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: sup-tckt-comment-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: sup-tckt-comment-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: sup-tckt-comment-fn-48039350-e3da-4e08-80c8-343f66779ebc
      namespace: default
  requestsPerPod: 10000
  resources: {}
