include:
- ./func/*
kind: ArchiveUploadSpec
name: func-jDtH

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-comment-fn-1d5aaef5-e343-48a4-9140-f1f946d82989
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: update-comment-ticket-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-jDtH
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-03-04T19:17:23Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-comment-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: update-comment-ticket-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_ticket_comments
    packageref:
      name: update-comment-fn-1d5aaef5-e343-48a4-9140-f1f946d82989
      namespace: default
  requestsPerPod: 1
  resources: {}
