apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: bb383b76-0762-4440-9d58-a08ad8e111cf
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-comment-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /update_comment
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /update_comment
