apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 665bd6df-4fa8-4fd7-aaee-3dc7fa5b49a7
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-comment-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /update_comments
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /update_comments
